import streamlit as st
import requests
import datetime
import os

# from exception.exceptions import TradingBotException
import sys

# Backend endpoint — inside the Sevalla container, FastAPI runs on localhost:8000.
# Override via the BACKEND_URL env var if needed.
BASE_URL = os.environ.get("BACKEND_URL", "http://localhost:8000")

st.set_page_config(
    page_title="PanthGuru — AI Travel Planner",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title(" PanthGuru")
st.caption("*The Path Guide — Your AI Travel planner*")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. which place do you want to explore now... ")
    submit_button = st.form_submit_button("pack the bags to voyage the 🌍 ")

if submit_button and user_input.strip():
    try:
        # # Show user message
        # Show thinking spinner while backend processes
        with st.spinner("helping you to plan your trip ..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# Here is your Travel Plan for all the days ...

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
           
            {answer}

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"